### ISSUE TITLE
How to add local Transforms to an Windows XXL Maltego Client

### ISSUE THREAD

**Issue by spacerat2001** [MISP/MISP-maltego#43] opened 2020-10-15 12:49 UTC
Hi, i am running a Windows 10 Client with Maltego XXL and need a connection to the local MISP instance. With the embedded Hub i have an Error Message. So our internal instance of MISP has no Internet connection. We have also an external MISP but without Company Knowledge TLP Red and amber.

Need a little help ;o)

Thx

**Comment by cvandeplas** [comment] 2020-10-15 13:34
You can indeed run MISP-maltego as local transform. I'm only unsure what the behaviour is with Windows, although the code should be platform agnostic. So in theory it is only a matter of installing the MISP-maltego package with pip3 on windows, and then import the package in Maltego. I expect you might encounter the same problems as reported in issue #33. 

Would you be able to try by to install it yourself and report back with error messages if you encounter some?
You can follow the instructions of the "local installation": https://github.com/MISP/MISP-maltego#local-transform-installation

**Comment by francsam01** [comment] 2020-11-17 22:27
Hi spacerat2001, were you be able to make the local Transform work in Windows? I'm using windows 10, I could create, import and launch the local transport but I cannot make a successfully connection against the local MISP Server.

Any advice will be helpful.

**Comment by cvandeplas** [comment] 2021-01-02 09:38
Closing as duplicate of #33

**Closed as completed by cvandeplas** 2021-01-02 09:38 UTC
Labels: support, Windows
